homeassistant:
  name: Opanez
  latitude: 44.462308
  longitude: 26.114623
  elevation: 84
  unit_system: metric
  currency: RON
  country: RO
  time_zone: "Europe/Bucharest"
  # packages: !include_dir_named integrations
  external_url: "https://ha.homtec.ro"
  internal_url: "http://192.168.1.210:8123"
  allowlist_external_dirs:
    - "/config/tmp"
    # - "/tmp"
  media_dirs:
    media: "/media"
    recordings: "/config/tmp"
  legacy_templates: false

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  studiocode:
    title: "StudioCode"
    url: "https://code-server.homtec.ro/?folder=/config/workspace"
    icon: mdi:microsoft-visual-studio-code
    require_admin: true
  # jenkins:
  #   title: "Jenkins"
  #   url: "https://jenkins.homtec.ro"
  #   icon: mdi:pipe-disconnected 
  #   require_admin: true
  portainer: 
    title: "Portainer"
    url: "https://portainer.homtec.ro"
    icon: mdi:docker
    require_admin: true
  # webmin:
  #   title: "Webmin"
  #   url: "https://webmin.homtec.ro/"
  #   icon: mdi:penguin
  #   require_admin: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.24.0.0/24
    - 192.168.1.0/24
# notify:
#   - name: FileNotifications
#     platform: file
#     filename: /config/fileNotifications.txt

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: "past_week_significant_earthquakes"

generic_hygrostat:
  - name: Toilet
    humidifier: fan.releu_ventilator_baie_mica_switch
    target_sensor: sensor.ewelink_th01_humidity
    min_humidity: 40
    max_humidity: 70
    target_humidity: 55
    dry_tolerance: 5
    wet_tolerance: 5
    device_class: "dehumidifier"
    min_cycle_duration:
      seconds: 300
    keep_alive:
      minutes: 15
    initial_state: true
    away_humidity: 50
    away_fixed: True
    sensor_stale_duration: 00:20:00
zone:
  - name: Judetului 13
    latitude: 44.457273426054954
    longitude: 26.114209592342377
    radius: 29.0
    icon: mdi:map-marker
  - name: Promenda-Sky Tower
    latitude: 44.47808977335862
    longitude: 26.103708744049076
    radius: 120.38016249893454
    icon: mdi:map-marker
  - name: Tulcea - Isaccei 29
    latitude: 45.17942495074601
    longitude: 28.79516333341599
    radius: 29.754978019457855
    icon: mdi:home-heart
  - name: Slanic-Grosani-Str Izvor
    latitude: 45.245936329454544
    longitude: 25.947850942611698
    radius: 81.2672158359266
    icon: mdi:greenhouse
  - name: Finii mici Bragadiru
    latitude: 44.38271975592732
    longitude: 26.027351617813114
    radius: 78.12210743224595
    icon: mdi:map-marker
  - name: AFI Europe - Pta Victoriei
    latitude: 44.45379469785626
    longitude: 26.08681688965803
    radius: 100.0
    icon: mdi:map-marker
  - name: Ion Mihalache - Lunch
    latitude: 44.45493196005009
    longitude: 26.081451773643497
    icon: mdi:map-marker
    radius: 114.40815916117002
  - name: America House
    latitude: 44.45236255734759
    longitude: 26.08213305473328
    icon: mdi:map-marker
    radius: 80.0
  - name: Medicover Victoriei
    latitude: 44.45093038218616
    longitude: 26.090190410614017
    radius: 63.0
    icon: mdi:map-marker
template: !include templates.yaml
switch:
  - platform: broadlink
    mac: '78:0F:77:48:3F:1D'
    switches:
      - name: "Samsung TV power"
        command_on: "JgCMAJaTFDYUNhQ2FBETEhMSExITEhM2FDYUNhQRExITEhMSExITERQ2FBEUERQRFBEUERMSEzYUERQ2FDYUNhQ2EzYUNhQABgaWkxM2FDYUNhQRFBEUERQRExITNxM2FDYUERQRFBEUERMSExITNhQRFBEUERQRFBEUERQ2ExITNxM2FDYUNhQ2EzcTAA0FAAAAAAAAAAAAAAAA"
      - name: "Samsung TV HDMI"
        command_on: "JgAYAZaTFDYUNRQ2FBEUERQRFBEUERQ2FDUUNhQRFBEUERQRFBEUNhQ1FBEVNRQRFBEUERQ2FBEUERQ1FBEUNhQ2FDYUERQABgWXkhQ2FDYUNhQRFBEUERQRExEUNhQ2FDYUERQRFBEUERMRFDYUNhQRFDYUERQRFBEUNRQRFBEUNhQRFDYUNhQ1FBEUAAYGlpMUNhQ1FDYUERQRFBEUERQRFDYUNRQ2FBEUERQRFBEUERQ2FDYUERM2FBEUERQRFDYUERQRFDYUERM2FDYUNhQRFAAGBZeSFDYUNhQ2FBEUERQRFBEUERQ1FDYUNhQRFBEUERQRFBEUNRQ2FBEUNhQRFBEUERQ2FBETERQ2FBEUNhQ2FDYUERMADQU="
      - name: "Samsung TV source"
        command_on: "JgDSAJaTFTUUNRQ2FBEUERQRFBEUERQ2FDUUNhUQFBEUERQRFBEUNhQRExITERQRFBEUERQRFBEUNhQ2EzYUNhQ2FDYUNhQABgWWkxQ2FDYUNRQRFBEUERQRFBEUNhQ2EzYUERQRFBEUERQRFDYUERQRExEUERQRFBEUERQRFDYUNhQ1FDYUNhQ2FDYUAAYFlpMUNhQ2FDUUERQRFBEUERQRFDYUNhQ1FBEUERQRFBEUERQ2FBEUERQRExITERQRFBEUERQ2FDYUNhM2FDYUNhQ2FAANBQAAAAAAAA=="
      - name: "Samsung TV Down"
        command_on: "JgCMAJaTFDYUNhQ2ExITERQRFBEUERQ2FDYUNhMSExITERQRFBEUNhQRFBEUERQRFDYTNhQRFBEUNhQ2FDYUNhMSExEUNhQABgaWkxQ2FDYTNhQRFBEUERQRFBEUNhQ2EzYUERQRFBEUERQRFDYUERQRExITEhM2FDYUERQRFDYUNhM3EzYUERQRFDYUAA0FAAAAAAAAAAAAAAAA"
      - name: "Samsung TV Up"
        command_on: "JgDSAJaTFDYTNxM2FBEUERQRFBEUERQ2EzcTNhQRFBEUERQRFBEUERQRExITEhMSEzYUNhQRFDYUNhM3EzcTNhQRFBEUNhQABgWXkxM2FDYUNhQRFBEUERQRExITNhQ2FDYUERQRFBEUERMSExITEhMRFBEUERQ2FDYUERQ2EzcTNhQ2FDYUERQREzcTAAYGlpMUNhQ2FDYTEhMSExITERQRFDYUNhQ2ExITEhMSExEUERQRFBEUERQRFBEUNhM3ExITNhQ2FDYUNhM3ExITERQ2FAANBQAAAAAAAA=="
      - name: "Samsung TV Left"
        command_on: "JgDSAJaTFTUUNhQ2FBEUERQRExEVEBQ2FDYVNRQRFBEUERQRExIUNRQRFDYUERQRFDYUNhQRFBAUNhQRFDYUNhQRFBEUNhMABgaWkxQ2FDYUNhQRFBEUERQRFBEUNRU1FTUUERQRFBEUERQRFDUVEBU1FRAUERQ2FDYUERQRFDUUERQ2FDYVEBQRFTUUAAYGlpMUNhM2FDYUERUQFBEUERQRFDYUNRU1FBEUERQRFBEUERQ2FBEUNhMRFBEUNhU1FBEUERU1FBEUNRU1FRAUERQ2FQANBQAAAAAAAA=="
      - name: "Samsung TV Enter"
        command_on: "JgCMAJaTFDYTNxM2FBEUERQRFBEUERQ2FDYTNhQRFBEUERQRFBEUERQRFBETNxMRFDYUNhQRFDYUNhM2FBEUNhQRFBEUNhQABgWXkhQ2FDYUNhQRFBEUERQRExITNhQ2FDYUERQRFBEUERQRExIUERMSEzYUERQ2FDYUERQ2EzYUNhQRFDYUERQRFDYUAA0FAAAAAAAAAAAAAAAA"
      - name: "Samsung TV Right"
        command_on: "JgCMAJaTFDYUNhQ2FBEUERMSExITEhM2FDYUNhQRFBEUERQRExITEhM2FBEUERQRFDYUNhQREzcTEhM2FDYUNhQRFBETNxMABgaWkxQ2FDYUNhQRExITEhMSExEUNhQ2FDYUERQRExITEhMSExEUNhQRFBEUERQ2FDYTEhM2FBEUNhQ2FDYUERMSEzYUAA0FAAAAAAAAAAAAAAAA"
      - name: "Samsung TV Menu"
        command_on: "JgDSAJeSFDYUNhQ2FBEUERQRFBEUERM2FDYUNhQRFBEUERQRFBETEhM2FRAUNhQ2FBEUERQRFDYTEhM2FBEUERU1FDYUNhQABgWXkxQ1FTUVNRQRFRAUERQRFBEUNhM2FTUUERQRFBEUERQRFBEUNhQRFDUUNhUQFBEUERQ2FBEUNhQRExEVNRQ2FDYVAAYFlpMUNhQ2FDUVEBQRFBEUERQRFTUUNhQ1FBEUERQRFBEUERQRFDYUERQ2FDUUERQRFBEUNhQRFDYUERQREzYUNhQ2FAANBQAAAAAAAA=="
      - name: "Samsung TV Guide"
        command_on: "JgDSAJaTFDYUNhM2FBEUERQRFBEUERQ2FDYTNhQRFBEUERQRFBEUNhQ2FDYTNhQRFBEUNhQRFRAUERQRFBEUNhM2FBEVNRQABgaWkxU1FDYUNRQSFBAUERUQFBEUNhQ2FDYUERMRFRAVEBQRFDYUNhQ2FDUUERUQFDYUERQRFBEUERQRFDYUNRQRFDYUAAYGlpMUNhQ2FDYTEhMRFBEUERQRFDYUNhQ2ExITEhMRFBEUERQ2FDYUNhQ2ExITERQ2FBEUERQRFBEUERQ2FDYTEhM2FAANBQAAAAAAAA=="
      - name: "Samsung TV Tools"
        command_on: "JgDSAJeSFDYUNhQ2FBEUERQRExITERQ2FDYUNhQRFBEUERQRExEUNhQ2FBEUNhQRFBEUNhMRFBEUERQ2FBEUNhQ2FBEUNRQABgaWkxQ2FDYUNhQRFBETERQRFBEUNhQ2FDYUERQRExITERQRFDYUNhQRFDYUERQRFDUUERQRFBEUNhQRFDYUNhQRFDUUAAYGlpMUNhQ2FDUUERQRFBEUERQRFDYUNhQ1FBITERQRFBEUERQ2FDYUERQ1FBITERQ2FBEUERQRFDYUERQ1FDYUERQ2FAANBQAAAAAAAA=="
      - name: "Samsung TV Info"
        command_on: "JgDSAJaTFTUUNhQ2FBEUERQQFBEUERQ2FDYUNhQRExITEhQQFBEUNhQ2FDYUNhQ1FBEVEBUQFBEUERUQFBEUERQ2FDUVNRQABgaWkxU1FDYUNhQRExITEhMRFBEVNRU1FDYUERQRFBEUERQQFTUVNRU1FDQWNhMSExEUERUQFBEUERQRFBEUNhQ2EzYUAAYGlpMUNhQ2FDYUERMSExITEhMRFDYUNhQ2FBEUERMSExITERQ2FDYUNhQ2FDYTEhMRFBEUERUQFBEUERQRFDYTNxM2FAANBQAAAAAAAA=="
      - name: "Samsung TV Ch List"
        command_on: "JgBGAJaTFDYUNhQ2ExITERQRFBEUERQ2FDYUNhMSExITERQRFBEUNhQ2FBEUNhMSEzYUNhQRFBEUERQ2FBETNhQRFBEUNhQADQUAAA=="
      - name: "Samsung TV Pre Ch"
        command_on: "JgDSAJeTFDUVNRU1FBEUERQRFBEUERQ1FTUUNhQRFBEUERQRFBEUNhM2FBEUERQ2FBEUERQRFBEUERQ1FDYUERQ2FDMXNhQABgaWkxQ2EzYUNhQRFBEUERQRFBEUNhQ2EzYUERQRFBEUERQRFDYUNhQRExITNhQRFBEUERQRFBEUNhQ2FBETNhQ2FDYUAAYGlpMVNRQ2FDYTEhMRFBEUERQRFDYUNhQ2FBETEhMRFBEUERQ2FDYUERQRFDYUERMSExEUERQRFDYUNhQRFDYUNRQ2FQANBQAAAAAAAA=="
      - name: "Samsung TV Program Up"
        command_on: "JgDSAJaTFDYTNxM2FBEUERQRFBEUERQ2FDYTNhQRFBEUERQRFBEUERQRFBETEhM2FBEUERQRFDYUNhQ2EzYUERQ2FDYUNhQABgWWkxQ2FDYUNhQRFBETEhMSExEUNhQ2FDYUERQRExITEhMRFBEUERQRFBEUNhQRFBETEhM2FDYUNhQ2FBEUNhM2FDYUAAYGlpMUNhM3EzYUERQRFBEUERQRFDYUNhM2FBEUERQRFBEUERQRFBEUERMSEzYUERQRFBEUNhQ2FDYTNhQRFDYUNhQ2FAANBQAAAAAAAA=="
      - name: "Samsung TV Program Down"
        command_on: "JgCMAJeSFTUUNhQ2FBEUERQRFBETEhM2FDYUNhQRFBEUERQRFBETEhM2FBEUERQ2FBEUERQRFDUUERQ2FDYUERQ2FDYTNhQABgaWkxQ2FDUUNhQRFBEUERQRFBEUNhQ1FDYUERQRFBEUERQRFBEUNRQSExEUNhQRFBEUERQ2FBEUNRQ2FBEUNhQ2FDYUAA0FAAAAAAAAAAAAAAAA"
      - name: "Samsung TV Mute"
        command_on: "JgDSAJaTFDYUNRQ2FBEUERQRFBEUERQ2FDUUNhQRFBEUERQRFBEUNhQ2EzYUNhQRFBEUERQRFBEUERQRFBEUNRU1FDYUNhQABgWXkhQ2FTUVNRQRFBEUERQRFBEUNRU1FDYVEBUQFBEUERQRFDUVNRQ2FDYUERQRFBEUERQRFBETERUQFTUVNRQ2FDYUAAYFlpMUNhQ2FDYUERQRFBETEhQQFDYVNRQ2FBEUERQRFBETERQ2FDYUNhQ2FBEUERMSExEUERQRFRAUERQ2FDYUNhM2FAANBQAAAAAAAA=="
      - name: "Samsung TV Volume Down"
        command_on: "JgDSAJaTFDYUNhQ2FBEUEBUQFBEVEBU1FDYUNhQRFBEUEBQRFBEUNhQ2FBEUNhQRFBAUERUQFBEUERQ2FRAUNhQ1FTUVNRUABgWWkxQ2EzYVNRQRFBEVEBQRFBEUNhQ1FDYVEBQRFRAUERQRFDYUNRQRFDYUERQRFBEUERQRFBEUNRUQFDYVNRU1FDYUAAYFlpMVNRQ2FDYUERQRFBETEhQQFDYUNhQ2FBEUERQRFBEUEBQ2FDYVEBQ2FBEUERQRFBAUERQRFDYUERQ2FDYUNRU1FQANBQAAAAAAAA=="
      - name: "Samsung TV Volume Up"
        command_on: "JgCMAJaTFDYTNhQ2FBEUERQRFBEUERQ2EzYUNhQRFBEUERQRFBEUNhQ2EzYUERQRFBEUERQRFBEUERQRFDYUNRU1FDYUNhQABgWXkhU1FTUVNRUQFBEUERQRFBETNhU1FTUUERQRFBEUERQRFDUVNRU1FRAUERQRFBEUERQRFBETERQ2FTUVNRQ2FDYTAA0FAAAAAAAAAAAAAAAA"
      - name: "LED RGB on"
        command_on: "JgBQAAABK5QUERQRFBIUERQSExIUERQSEzYUNhQ2FDYVEBQ2EzcTNxQ2EzYUEhQRFBITEhQRFBITEhQRFDYTNxM3FDYTNhQ2FAAFSAABK0kUAA0FAAAAAAAAAAA="
      - name: "LED RGB off"
        command_on: "JgBQAAABK5MVERQRFRAVERQRFRAVERUQFTUVNRU1FDUVERU0FTUVNRURFDUVERUQFREUERUQFREUNRURFTUUNRU1FTUVNRU1FQAFRwABLEgVAA0FAAAAAAAAAAA="
      - name: "LED RGB dim"
        command_on: "JgBYAAABLJIVERUQFhAVEBUQFhAVEBUQFjQVNRU1FjQVEBU1FjQVNBY0FhAVEBUQFhAVEBUQFhAVEBU1FTUVNRU0FjQVNRU1FQAFRwABLEgVAAxgAAEuRhcADQU="
      - name: "LED RGB brite"
        command_on: "JgBYAAABK5MWEBUQFRAWEBUQFREVEBUQFjQVNRY0FTUVEBU1FTUWNBUQFRAWEBUQFRAWEBUQFREVNBY0FTUVNRU1FTUVNBY0FQAFSAABLEgVAAxhAAErSBYADQU="
      - name: "LED RGB red"
        command_on: "JgBQAAABK5MWEBYPFg8WEBYPFRAWEBUQFTUVNRU1FjMWEBU1FTQWNBURFRAWNBUQFhAWDxYPFhAVNBU1FhAVNBY0FjQVNRY0FQAFRwABLEgVAA0FAAAAAAAAAAA="
      - name: "LED RGB green"
        command_on: "JgBYAAABK5MVEBYQFRAVERQRFRAVERUQFTUVNRU0FTUVERU0FjQVNRU1FRAWNBURFRAVEBYQFRAVEBY0FhAVNBY0FjQVNRU1FQAFRwABLEgWAAxgAAEsSBUADQU="
      - name: "LED RGB blue"
        command_on: "JgBYAAABK5QUERUQFREUERUQFREVEBURFDUWNBY0FjMXDxY0EzcWNBYPFjQWNBMSFhAVEBYPFhAVNBYQFg8WNBM3FjQWNBU0FgAFRwABK0kWAAxgAAErSRYADQU="
      - name: "LED RGB white"
        command_on: "JgBYAAABLpMVEBURFRAVEBURFRAVEBYQFTQVNRU1FTUVEBU1FTUVNRU1FTUVNBURFRAVERQRFRAVERUQFRAVNRU1FTUVNRU1FQAFRwABLEgVAAxhAAEsSBUADQU="
      - name: "LED RGB red-orange"
        command_on: "JgBYAAABLJMUERURFBEVEBURFBEVEBURFDUVNRU1FTUVEBU1FTUVNRQRFREUERQ2FBEVEBURFBEVNRU1FDQWERU1FDYUNRU1FQAFRwABLEgVAAxgAAEsSBUADQU="
      - name: "LED RGB orange"
        command_on: "JgBYAAABK5MVERQRFRAVERQRFRAVERQRFTUVNRU0FTUVERU0FTUVNRURFBEVNRU1FBEVEBURFBEVNRU1FBEVEBU1FTUVNRU1FAAFSAABLEgVAAxhAAErSRQADQU="
      - name: "LED RGB orange-yellow"
        command_on: "JgBQAAABLJIXDxUQFRAWEBUQFREVEBUQFjQVNRY0FTQWEBU1FTQWNBURFg8WDxYQFTUVEBUQFw8WMxczFjQWNBUQFzMVNRU1FQAFRwABLkYVAA0FAAAAAAAAAAA="
      - name: "LED RGB yellow"
        command_on: "JgBYAAABLJITExUQFRESExMSExMSExMSEzcTNxU1FTUVEBU1EzcVNRUQExIWNBUREjcVERITFRATNxU1Fg8TNxYQEjcTNxY0EwAFSgABKkkWAAxgAAEpShUADQU="
      - name: "LED RGB green2"
        command_on: "JgBQAAABK5MXDxUQFhAVEBUQFhAVEBUQFjQVNRY0FTUVEBU1FjMWNBU1FREVEBU1FRAWDxYQFRAWEBU0FjQVERU0FTUVNRU1FQAFRwABLEgVAA0FAAAAAAAAAAA="
      - name: "LED RGB green3"
        command_on: "JgBYAAABLJMVEBURFBEVERQRFBEVERQRFTUUNhQ1FTUVERQ2FDUVNRU1FREUNRU1FREUERQRFREUERQ2FBEVERQ1FTUVNRU1FAAFSAABLEgVAAxhAAErSRQADQU="
      - name: "LED RGB green4"
        command_on: "JgBcAAABLZITEhUREhMVERQRExITExQRFDYTNxI3EzcTExI4EzYTNxQ2ExIUEhUQFTUTEhURFRAVEBY0FTUTNxURFTQVNRY0EgAFSgABKkoVAAiZCQADvwABK0kUAA0FAAAAAAAAAAAAAAAA"
      - name: "LED RGB green5"
        command_on: "JgBYAAABK5QUERQSFBEUERQSFBEUEhMSFDYTNxM2FDYUEhQ2EzYTNxQ2FBITNhQSFDYSExQRFBIUERQ2FBEUNhQSEzYUNhQ2EwAFSgABKkoTAAxjAAErSBQADQU="
      - name: "LED RGB blue2"
        command_on: "JgBQAAABKpUWDxYQFRAWDxYQFg8WEBUQFjQTNxY0FTUSExU1EzcUNhQRFTUVEBU1FRETEhUQExMUNhITFTUVEBM3FjQTNxU1FQAFSQABK0kUAA0FAAAAAAAAAAA="
      - name: "LED RGB blue-indigo"
        command_on: "JgBYAAABKZUXDxUQFhAWDxYPFhAVEBYPFzMWNBU1FTUVEBU1FTUVNRUQFTUUNhU1Fg8VEBYQFRAVNRYPFhAVEBU1FTUVNRU0FgAFRwABK0kWAAxgAAEqShcADQU="
      - name: "LED RGB indigo-blue"
        command_on: "JgBYAAABK5QVEBURFBEVEBURFRAVEBYQFTUVNBczFTUVEBczFzMVNRYPFzMTExYPFjQVEBYQFg8WNBUQFjQVNRUQFjQVNRU1FQAFRwABLEgWAAxhAAErSRUADQU="
      - name: "LED RGB indigo"
        command_on: "JgBYAAABKpQUEhQRFBEUEhQRFBITEhQRFDYTNxM3EzcTEhQ2EzcUNRQSFDYTNxMSFDYUERQSExIUNhMSFBEUNhQSFDUUNhQ2FAAFSQABK0kTAAxjAAErSRQADQU="
      - name: "LED RGB flash"
        command_on: "JgBYAAABK5QWDxYQFRAVEBYQFRAWEBUQFTUVNRU1FTQWEBU1FTQWNBY0FTUVEBY0FREVEBUQFhAVEBYQFTQWEBU1FTUVNBY0FQAFSAABLEgVAAxhAAEqShYADQU="
      - name: "LED RGB strobe"
        command_on: "JgBYAAABKpQUEhQRFBITEhQRFBIUERQRFDYUNhM3FDYTEhQ2FDYTNxQ2FDYTNhQ2FBITEhQRFBIUERQRFBIUERQ2FDYTNRU3EwAFSQABK0kUAAxiAAErSRQADQU="
      - name: "LED RGB fade"
        command_on: "JgBYAAABLJMVEBURFBEVEBURFRAVERQRFTUUNhQ1FTUVERQ2FDUVNRU1FTUVEBURFTUUERUQFREUERUQFTUVNRUQFTUVNRU1FQAFSAABK0gVAAxhAAErSRcADQU="
      - name: "LED RGB smooth"
        command_on: "JgBYAAABLJITExUQFRAWEBQRFRAVERUQFTUVNRM3EjcWEBM3FTQVNRY0EzcTNxMSEzcTEhUREhMVEBQSFBEVNRUQFTUVNRU1EwAFSQABK0kUAAxjAAEqSRQADQU="
sensor:
  platform: feedparser
  name: Biziday Feed
  feed_url: 'https://www.biziday.ro/feed/'
  date_format: '%a, %d %b %Y %H:%M:%S %Z'
  scan_interval:
    hours: 4
  inclusions:
    - title
    - link
    - description
    - pubDate
    - image
  exclusions:
    - language